# Generated by Django 6.0.2 on 2026-02-16 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial_product_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notify_at",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Уведомление будет отправлено, если цена продукта упадет ниже этого значения",
                        max_digits=10,
                        null=True,
                        verbose_name="Пороговая цена",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "last_notified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последнее уведомление"
                    ),
                ),
                (
                    "notify_cooldown_hours",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Минимум часов между уведомлениями",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="product.product",
                        verbose_name="Продукт",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подписка на продукт",
                "verbose_name_plural": "Подписки на продукты",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "product"), name="unique_user_product"
                    )
                ],
            },
        ),
    ]
